In [2]:
import pandas as pd
from PyPDF2 import PdfReader as PDFReader
import os

In [20]:
dct = {}
new_lst = []
for pdfs in os.listdir('./GENDER W- TOV'):
    if pdfs[-4:] == '.pdf':
        lst = []
        cur = PDFReader(f'./GENDER W- TOV/{pdfs}')
        ctx = cur.pages[0].extract_text().split('\n')
        for i in range(12, 21):
            if i <= 15 or i == 17 or i == 19:
                lst.append(ctx[i])
            elif i == 16 or i == 18:
                lst.append(ctx[i][:-1])
                lst.append(ctx[i][-1])
            else:
                lst.append(ctx[i][:7])
                lst.append(ctx[i][7:])
        df = pd.DataFrame(lst)
        df = df.transpose()
        # print(cur.pages[0].extract_text().split('\n')[i])
        new_lst.append(df)
res_col = pd.concat(new_lst, axis=0)

In [21]:
res_col.head()

,0,1,2,3,4,5,6,7,8,9,10,11
0,50,"4,414","5,051","3,183","3,834",0,"9,465",72.11 %,0,"7,017",74.14 %,75.91 %
0,32,"2,763","3,074","2,044","2,300",0,"5,837",73.98 %,0,"4,344",74.42 %,74.82 %
0,30,"2,808","3,001","2,161","2,328",0,"5,809",76.96 %,0,"4,489",77.28 %,77.57 %
0,139,"12,231","14,223","7,606","9,392",0,"26,454",62.19 %,0,"16,998",64.25 %,66.03 %
0,54,"4,694","5,247","3,496","4,020",1,"9,942",74.48 %,1,"7,517",75.61 %,76.62 %

In [22]:
res_col.columns = ['TOTAL NUMBER OF PRECINCTS',
                  'TOTAL NUMBER OF REGISTERED MALES',
                  'TOTAL NUMBER OF REGISTERED FEMALES',
                  'TOTAL NUMBER OF REGISTERED VOTERS WITH INVALID SEX',
                  'TOTAL NUMBER OF REGISTERED VOTERS',
                   'TOTAL NUMBER OF ACTUALLY VOTED MALES',
                   'TOTAL NUMBER OF ACTUALLY VOTED FEMALES',
                   'TOTAL NUMBER OF ACTUALLY VOTED WITH INVALID SEX',
                   'TOTAL NUMBER OF VOTERS WHO ACTUALLY VOTED',
                   'PERCENTAGE OF MALE VOTED',
                   'PERCENTAGE OF FEMALE VOTED',
                   'PERCENTAGE OF ALL VOTERS',
                  ]

In [23]:
res_col.head()

,TOTAL NUMBER OF PRECINCTS,TOTAL NUMBER OF REGISTERED MALES,TOTAL NUMBER OF REGISTERED FEMALES,TOTAL NUMBER OF REGISTERED VOTERS WITH INVALID SEX,TOTAL NUMBER OF REGISTERED VOTERS,TOTAL NUMBER OF ACTUALLY VOTED MALES,TOTAL NUMBER OF ACTUALLY VOTED FEMALES,TOTAL NUMBER OF ACTUALLY VOTED WITH INVALID SEX,TOTAL NUMBER OF VOTERS WHO ACTUALLY VOTED,PERCENTAGE OF MALE VOTED,PERCENTAGE OF FEMALE VOTED,PERCENTAGE OF ALL VOTERS
0,50,"4,414","5,051","3,183","3,834",0,"9,465",72.11 %,0,"7,017",74.14 %,75.91 %
0,32,"2,763","3,074","2,044","2,300",0,"5,837",73.98 %,0,"4,344",74.42 %,74.82 %
0,30,"2,808","3,001","2,161","2,328",0,"5,809",76.96 %,0,"4,489",77.28 %,77.57 %
0,139,"12,231","14,223","7,606","9,392",0,"26,454",62.19 %,0,"16,998",64.25 %,66.03 %
0,54,"4,694","5,247","3,496","4,020",1,"9,942",74.48 %,1,"7,517",75.61 %,76.62 %

In [25]:
res_col.to_csv('municipal_summary_per_barangay_2023.csv')